org: pratappadhy2005
app: auth-service
service: auth-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2

functions:
  signUp:
    handler: handlers/signUp.signUp
    events:
      - httpApi:
          path: /sign-up
          method: post
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  
