org: pratappadhy2005
app: greet-api
service: greet-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /greet
          method: get
