org: pratappadhy2005
app: greet-api
service: greet-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2

functions:
  greet:
    handler: index.greet
    events:
      - httpApi:
          path: /greet
          method: get
  anotherGreet:
    handler: anotherGreet.anotherGreet
    events:
      - httpApi:
          path: /another-greet
          method: post
